#define TAILLE_BLOC         16
#define NB_BLOCS_LARGEUR    50 //NB_BLOCS_LARGEUR > NB_BLOCS_HAUTEUR
#define NB_BLOCS_HAUTEUR    40
#define LARGEUR_FENETRE     TAILLE_BLOC * NB_BLOCS_LARGEUR
#define HAUTEUR_FENETRE     TAILLE_BLOC * NB_BLOCS_HAUTEUR
#define COULEUR_ECRAN       32  // 8, 16 ou 32

    enum {VIDE, MUR, JOUEUR1, JOUEUR2};
